export const honors = [
  {
    id: 2,
    type: "license",
    title: "宝时得（威克士)授权书",
    image: "/images/honors/2.png",
  },
  {
    id: 3,
    type: "license",
    title: "贝力（福岚德）授权书",
    image: "/images/honors/3.png",
  },
  {
    id: 4,
    type: "license",
    title: "力克达授权书",
    image: "/images/honors/4.png",
  },
  {
    id: 5,
    type: "license",
    title: "威易迅（肯普）授权书",
    image: "/images/honors/5.png",
  },
  {
    id: 6,
    type: "license",
    title: "美沃奇&南航授权书",
    image: "/images/honors/6.png",
  },
  {
    id: 7,
    type: "license",
    title: "美沃奇&重工授权书",
    image: "/images/honors/7.png",
  },
  {
    id: 8,
    type: "license",
    title: "实耐宝授权书",
    image: "/images/honors/8.png",
  },
  {
    id: 9,
    type: "license",
    title: "瓦格纳尔授权书",
    image: "/images/honors/9.png",
  },

  {
    id: 12,
    type: "license",
    title: "CLECO授权书",
    image: "/images/honors/12.png",
  },
  {
    id: 13,
    type: "license",
    title: "玛驰授权书",
    image: "/images/honors/13.png",
  },
  {
    id: 16,
    type: "certificate",
    title: "企业信用评价AAA级证书",
    image: "/images/honors/1-2.png",
  },
  {
    id: 15,
    type: "certificate",
    title: "企业信用等级证书",
    image: "/images/honors/1-1.png",
  },
  {
    id: 14,
    type: "certificate",
    title: "ISO9001证书",
    image: "/images/honors/ISO9001.png",
  },
  {
    id: 17,
    type: "certificate",
    title: "企业信用等级证书",
    image: "/images/honors/1-3.png",
  },
  {
    id: 18,
    type: "certificate",
    title: "质量服务诚信企业",
    image: "/images/honors/1-4.png",
  },
  {
    id: 19,
    type: "certificate",
    title: "重合同守信⽤企业",
    image: "/images/honors/1-5.png",
  },
  {
    id: 20,
    type: "certificate",
    title: "诚信经营⽰范企业",
    image: "/images/honors/1-6.png",
  },
  {
    id: 21,
    type: "certificate",
    title: "重质量守信⽤企业",
    image: "/images/honors/1-7.png",
  },
  {
    id: 22,
    type: "certificate",
    title: "重服务守信⽤企业",
    image: "/images/honors/1-8.png",
  },
  {
    id: 23,
    type: "certificate",
    title: "企业资信等级证书",
    image: "/images/honors/1-9.png",
  },
];
