export interface ProductItem {
  id: string;
  title: string;
  category: string;
  price?: number;
  description: string;
  details: string;
  images: string[];
  features: string[];
  content?: string[];
}

export const ProductList: ProductItem[] = [
  {
    id: "1",
    title: "电动磁力钻",
    category: "电动工具",
    description:
      "磁力钻钻孔效率高，能保证加工精度，操作简单，使用方便安全，主要用于手电钻和钻床不适宜进行钻削加工的场合。",
    details:
      "<p>磁力钻钻孔效率高，能保证加工精度，操作简单，使用方便安全，主要用于手电钻和钻床不适宜进行钻削加工的场合。</p>",
    images: [
      "/images/product/ddclz/clz_1.jpg",
      "/images/product/ddclz/clz_2.jpg",
    ],
    features: ["重量轻，方便携带", "功能全，二档变速", "自动内部冷却装置"],
    content: [
      "/images/product/ddclz/详情_01.jpg",
      "/images/product/ddclz/详情_02.jpg",
      "/images/product/ddclz/详情_03.jpg",
      "/images/product/ddclz/详情_04.jpg",
      "/images/product/ddclz/详情_05.jpg",
      "/images/product/ddclz/详情_06.jpg",
      "/images/product/ddclz/详情_07.jpg",
    ],
  },
  {
    id: "2",
    title: "角磨机",
    category: "电动工具",
    price: 86000,
    description:
      "角磨机是一种利用玻璃钢切削和打磨的手提式电动工具，主要用于切割、研磨及刷磨金属与石材等",
    details:
      "<p>角磨机是一种利用玻璃钢切削和打磨的手提式电动工具，主要用于切割、研磨及刷磨金属与石材等</p>",
    images: ["/images/product/ddjmj/主图600-600.jpg"],
    features: [
      "不同装备如带自动速度调节装备或者不带",
      "不同功率等级",
      "一样的产品质量",
    ],
    content: [
      "/images/product/ddjmj/详情_01.jpg",
      "/images/product/ddjmj/详情_02.jpg",
      "/images/product/ddjmj/详情_03.jpg",
      "/images/product/ddjmj/详情_04.jpg",
    ],
  },
  {
    id: "3",
    title: "手持空心钻",
    category: "电动工具",
    price: 198000,
    description: "手持空心钻",
    details: "<p>手持空心钻</p>",
    images: ["/images/product/sckxz/1.jpg", "/images/product/sckxz/2.jpg"],
    features: [],
    content: [
      "/images/product/sckxz/详情_01.jpg",
      "/images/product/sckxz/详情_02.jpg",
    ],
  },
  {
    id: "4",
    title: "手电钻",
    category: "电动工具",
    price: 198000,
    description: "手电钻",
    details: "<p>手电钻</p>",
    images: ["/images/product/ddsdz/主图600-600.jpg"],
    features: [],
    content: ["/images/product/ddsdz/详情.jpg"],
  },
  {
    id: "5",
    title: "移动式砂带机",
    category: "电动工具",
    price: 198000,
    description: "移动式砂带机",
    details: "<p>移动式砂带机</p>",
    images: ["/images/product/ydssdj/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/ydssdj/详情_01.jpg",
      "/images/product/ydssdj/详情_02.jpg",
      "/images/product/ydssdj/详情_03.jpg",
    ],
  },
  {
    id: "6",
    title: "气动扳手",
    category: "气动工具",
    price: 198000,
    description: "气动扳手",
    details: "<p>气动扳手</p>",
    images: ["/images/product/qdbs/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qdbs/详情_01.jpg",
      "/images/product/qdbs/详情_02.jpg",
      "/images/product/qdbs/详情_03.jpg",
      "/images/product/qdbs/详情_04.jpg",
      "/images/product/qdbs/详情_05.jpg",
      "/images/product/qdbs/详情_06.jpg",
    ],
  },
  {
    id: "7",
    title: "气动冲击扳手",
    category: "气动工具",
    price: 198000,
    description: "气动冲击扳手",
    details: "<p>气动冲击扳手</p>",
    images: ["/images/product/qdcjbs/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qdcjbs/详情_1.jpg",
      "/images/product/qdcjbs/详情_2.jpg",
    ],
  },
  {
    id: "8",
    title: "气动锤子",
    category: "气动工具",
    price: 198000,
    description: "气动锤子",
    details: "<p>气动锤子</p>",
    images: ["/images/product/qdcz/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qdcz/详情_01.jpg",
      "/images'/product/qdcz/详情_02.jpg",
    ],
  },
  {
    id: "9",
    title: "气动打磨机",
    category: "气动工具",
    price: 198000,
    description: "气动打磨机",
    details: "<p>气动打磨机</p>",
    images: ["/images/product/qddmj/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qddmj/详情_01.jpg",
      "/images/product/qddmj/详情_02.jpg",
      "/images/product/qddmj/详情_03.jpg",
      "/images/product/qddmj/详情_04.jpg",
      "/images/product/qddmj/详情_05.jpg",
      "/images/product/qddmj/详情_06.jpg",
      "/images/product/qddmj/详情_07.jpg",
      "/images/product/qddmj/详情_08.jpg",
      "/images/product/qddmj/详情_09.jpg",
      "/images/product/qddmj/详情_10.jpg",
      "/images/product/qddmj/详情_11.jpg",
      "/images/product/qddmj/详情_12.jpg",
      "/images/product/qddmj/详情_13.jpg",
    ],
  },
  {
    id: "10",
    title: "气动管道螺母工具",
    category: "气动工具",
    price: 198000,
    description: "气动管道螺母工具",
    details: "<p>气动管道螺母工具</p>",
    images: ["/images/product/qdgdlmgj/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qdgdlmgj/详情_1.jpg",
      "/images/product/qdgdlmgj/详情_2.jpg",
    ],
  },
  {
    id: "11",
    title: "气动棘轮扳手",
    category: "气动工具",
    price: 198000,
    description: "气动棘轮扳手",
    details: "<p>气动棘轮扳手</p>",
    images: ["/images/product/qdjlbs/主图.jpg"],
    features: [
      "依据工位螺栓尺寸、螺栓等级、目标扭矩、硬软接合程度选择匹配的工具型号。",
      "狭小空间螺栓应用",
      "最大扭力从小到大规格，肯普皆有对应工具机种。",
    ],
    content: [
      "/images/product/qdjlbs/详情_1.jpg",
      "/images/product/qdjlbs/详情_2.jpg",
    ],
  },
  {
    id: "12",
    title: "气动角磨机",
    category: "气动工具",
    price: 198000,
    description: "气动角磨机",
    details: "<p>气动角磨机</p>",
    images: ["/images/product/qdjmj/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qdjmj/详情_01.jpg",
      "/images/product/qdjmj/详情_02.jpg",
    ],
  },
  {
    id: "13",
    title: "全自动气动起子",
    category: "气动工具",
    price: 198000,
    description: "全自动气动起子",
    details: "<p>全自动气动起子</p>",
    images: ["/images/product/qzdqdqz/主图600-600.jpg"],
    features: [],
    content: [
      "/images/product/qzdqdqz/详情_01.jpg",
      "/images/product/qzdqdqz/详情_02.jpg",
      "/images/product/qzdqdqz/详情_03.jpg",
      "/images/product/qzdqdqz/详情_04.jpg",
    ],
  },
  {
    id: "14",
    title: "气动液压拉铆螺母枪",
    category: "气动工具",
    price: 198000,
    description: "气动液压拉铆螺母枪",
    details: "<p>气动液压拉铆螺母枪</p>",
    images: [
      "/images/product/qdyylmlmq/主图_1.jpg",
      "/images/product/qdyylmlmq/主图_2.jpg",
    ],
    features: [
      "螺帽尺寸大小与材质软硬跟机种的拉力相关",
      "针对固定铆螺母尺寸建议如下：",
      "不锈钢材质M8以下建议选择 A-ENT-HM2-S06T157",
      "不锈纲材质Ｍ8以上建议选择 A-ENT-HM2-S08T245",
      "比不锈钢材质较软或韧性低的其他材质没有太大差异。",
    ],
    content: [
      "/images/product/qdyylmlmq/详情_01.jpg",
      "/images/product/qdyylmlmq/详情_02.jpg",
      "/images/product/qdyylmlmq/详情_03.jpg",
    ],
  },
  {
    id: "15",
    title: "锤子",
    category: "手动工具",
    price: 198000,
    description: "锤子",
    details: "<p>锤子</p>",
    images: [
      "/images/product/sdcz/主图_1.jpg",
      "/images/product/sdcz/主图_2.jpg",
    ],
    features: ["达到美国ANSI标准", "锤头可更换，耐敲击、防滑、不可燃"],
    content: [
      "/images/product/sdcz/14捶子类152.jpg",
      "/images/product/sdcz/14捶子类153.jpg",
      "/images/product/sdcz/14捶子类154.jpg",
      "/images/product/sdcz/14捶子类155.jpg",
    ],
  },
  {
    id: "16",
    title: "多功能工具车",
    category: "手动工具",
    price: 198000,
    description: "多功能工具车",
    details: "<p>多功能工具车</p>",
    images: ["/images/product/dgngjc/主图.jpg"],
    features: [
      "定制的轮胎、重载悬挂和能有效控制刹车的手柄，让工作变得省时省力",
    ],
    content: [
      "/images/product/dgngjc/详情_1.jpg",
      "/images/product/dgngjc/详情_2.jpg",
      "/images/product/dgngjc/详情_3.jpg",
      "/images/product/dgngjc/详情_4.jpg",
    ],
  },
  {
    id: "17",
    title: "活动扳手",
    category: "手动工具",
    price: 198000,
    description: "活动扳手",
    details: "<p>活动扳手</p>",
    images: [
      "/images/product/hdbs/主图_1.jpg",
      "/images/product/hdbs/主图_2.jpg",
    ],
    features: [
      "定制的轮胎、重载悬挂和能有效控制刹车的手柄，让工作变得省时省力",
    ],
    content: [
      "/images/product/hdbs/9-106.jpg",
      "/images/product/hdbs/9-107.jpg",
      "/images/product/hdbs/9-108.jpg",
      "/images/product/hdbs/9-109.jpg",
    ],
  },
];
